### ISSUE TITLE
Migration Plan: AWS Lambda Java to Containerized Spring Boot (Clean Architecture)

### ISSUE THREAD

**Issue by jiratouchmhp** [jiratouchmhp/demo-java-aws-lamda-to-azure#9]
# Migration Plan: AWS Lambda Java to Containerized Spring Boot (Clean Architecture)

**🎯 Target Platforms:** Azure Container Apps, Azure AKS, Azure App Services (NOT AWS)

This comprehensive migration will be completed in **6 detailed steps**, each with specific instructions and cleanup procedures to ensure a smooth transition from AWS Lambda to a containerized Spring Boot application following Clean Architecture principles.

---

### 🔍 Assessment Phase
**Inventory all existing AWS Lambda functions and document:**
- [ ] Handler class identification
- [ ] Trigger type analysis (API Gateway, SQS, etc.)
- [ ] Input/output structure mapping
- [ ] External dependencies audit (S3, DynamoDB, etc.)

### 🚀 Spring Boot Project Creation
**Create new Spring Boot project:**
- [ ] Use https://start.spring.io with Web + Spring Boot 3.x
- [ ] **Required Dependencies:**
  - `spring-boot-starter-web`
  - `spring-boot-starter-test`
  - `spring-boot-starter-data-jpa`
  - `spring-boot-starter-validation`
  - `spring-boot-starter-actuator`
  - `springdoc-openapi-starter-webmvc-ui`
  - `lombok`
- [ ] Package name: `com.example.migration`
- [ ] Application class: `MigrationApplication.java`

### 📁 Clean Architecture Folder Structure
```
src/main/java/com/example/migration/
├── MigrationApplication.java
├── domain/              # Business entities and interfaces (framework-free)
├── application/         # Use cases and business logic orchestration
├── adapter/            # Infrastructure implementations
├── controller/         # REST API layer
└── dto/               # Data transfer objects
```

### ⚙️ Environment Configuration
- [ ] **Configure `application.yml` for environments:**
```yaml
spring:
  profiles:
    active: dev
  application:
    name: migration-api

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
```

---

### 📐 Domain Layer Implementation
**Move business logic from Lambda handler to use case services:**

- [ ] **Create Domain Entities (Plain Java classes):**
```java
// Example: User domain entity
public class User {
    private String id;
    private String name;
    private String email;
    
    // constructors, getters, setters
}
```

- [ ] **Define Port Interfaces:**
```java
// Example: Repository interface (port)
public interface UserRepository {
    User save(User user);
    Optional<User> findById(String id);
    List<User> findAll();
    void deleteById(String id);
}
```

### 🎯 Application Layer Implementation
- [ ] **Create Service Classes (Business orchestration logic):**
```java
// Example: Application service
@Service
@Transactional
public class UserService {
    private final UserRepository userRepository;
    
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }
    
    public User createUser(User user) {
        // business logic validation
        return userRepository.save(user);
    }
    
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }
}
```

### 🧹 Cleanup Tasks
- [ ] Archive existing Lambda business logic for reference
- [ ] Document mapping between Lambda functions and new services

---

### 💾 Persistence Adapter
- [ ] **Create Spring Data JPA Repository:**
```java
// Example: JPA repository interface
public interface UserJpaRepository extends JpaRepository<UserEntity, String> {
    List<UserEntity> findByNameContainingIgnoreCase(String name);
}
```

- [ ] **Implement Repository Adapter:**
```java
// Example: Repository adapter implementation
@Repository
public class UserPersistenceAdapter implements UserRepository {
    private final UserJpaRepository jpaRepository;
    private final UserMapper userMapper;
    
    public UserPersistenceAdapter(UserJpaRepository jpaRepository, UserMapper userMapper) {
        this.jpaRepository = jpaRepository;
        this.userMapper = userMapper;
    }
    
    @Override
    public User save(User user) {
        UserEntity entity = userMapper.toEntity(user);
        UserEntity savedEntity = jpaRepository.save(entity);
        return userMapper.toDomain(savedEntity);
    }
    
    // Additional methods...
}
```

### 🌐 External Service Adapters
- [ ] **Create external service interfaces and implementations:**
  - File storage (replace S3 with Azure Blob Storage)
  - Database connections
  - Third-party API integrations
- [ ] Annotate with `@Repository` or `@Component`

### 🧹 Cleanup Tasks
- [ ] Remove AWS SDK dependencies from `pom.xml`
- [ ] Replace AWS service calls with Azure equivalents

---

### 🛠️ REST Controller Implementation
**Replace Lambda triggers with `@RestController` endpoints:**

- [ ] **Create REST Controllers:**
```java
// Example: User REST controller
@RestController
@RequestMapping("/api/v1/users")
@Validated
public class UserController {
    private final UserService userService;
    private final UserMapper userMapper;
    
    public UserController(UserService userService, UserMapper userMapper) {
        this.userService = userService;
        this.userMapper = userMapper;
    }
    
    @PostMapping
    @Operation(summary = "Create a new user")
    @ApiResponse(responseCode = "201", description = "User created successfully")
    public ResponseEntity<UserResponse> createUser(
            @Valid @RequestBody CreateUserRequest request) {
        User user = userMapper.toDomain(request);
        User savedUser = userService.createUser(user);
        return ResponseEntity.status(HttpStatus.CREATED)
                .body(userMapper.toResponse(savedUser));
    }
    
    @GetMapping
    @Operation(summary = "Get all users")
    public ResponseEntity<List<UserResponse>> getAllUsers() {
        List<User> users = userService.getAllUsers();
        return ResponseEntity.ok(userMapper.toResponseList(users));
    }
}
```

### 📝 DTO Implementation
- [ ] **Create Request/Response DTOs:**
```java
// Example: Request DTO
public record CreateUserRequest(
    @NotBlank(message = "Name is required")
    String name,
    
    @Email(message = "Email must be valid")
    @NotBlank(message = "Email is required")
    String email
) {}

// Example: Response DTO
public record UserResponse(
    String id,
    String name,
    String email,
    LocalDateTime createdAt
) {}
```

### 🗺️ Mapping Implementation
- [ ] **Use OpenAPI annotations via `springdoc-openapi-ui`**
- [ ] **Map request/response DTOs to domain models**
- [ ] **Use proper HTTP verbs, response codes, and validation**

### 🧹 Cleanup Tasks
- [ ] Remove Lambda handler classes after migration verification
- [ ] Archive Lambda controller logic for reference

---

### 🔀 Function-by-Function Migration Strategy
**Migrate Lambda functions incrementally:**

- [ ] **For each Lambda function:**
  - Extract business logic → domain/application layer
  - Create matching REST controller
  - Write comprehensive unit + integration tests
  - Compare behavior against Lambda (input/output validation)

### 🛡️ Enhanced Error Handling
- [ ] **Implement Global Exception Handler:**
```java
@RestControllerAdvice
public class GlobalExceptionHandler {
    private static final Logger log = LoggerFactory.getLogger(GlobalExceptionHandler.class);
    
    @ExceptionHandler(NotFoundException.class)
    public ResponseEntity<ApiError> handleNotFound(NotFoundException ex) {
        log.warn("Resource not found: {}", ex.getMessage());
        return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(new ApiError(ex.getMessage()));
    }
    
    @ExceptionHandler(ValidationException.class)
    public ResponseEntity<ApiError> handleValidation(ValidationException ex) {
        log.warn("Validation error: {}", ex.getMessage());
        return ResponseEntity.badRequest()
                .body(new ApiError(ex.getMessage()));
    }
    
    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiError> handleGeneric(Exception ex) {
        log.error("Unexpected error occurred", ex);
        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ApiError("An unexpected error occurred"));
    }
}
```

### ✅ Validation Implementation
- [ ] **Add Input Validation:**
  - Use `@Valid` with Jakarta validation annotations
  - Implement custom validators for business rules

### 📊 Structured Logging
- [ ] **Configure Structured Logging:**
  - Use SLF4J with Logback or Log4j2
  - Add correlation IDs for request tracing
  - Configure different log levels per environment

### 🧪 Testing Strategy
- [ ] **Write comprehensive tests:**
  - Unit tests for each service method
  - Integration tests for REST endpoints
  - Repository tests for data access
- [ ] **Test in parallel with Lambda if needed**

### 🧹 Cleanup Tasks
- [ ] Remove Lambda test files
- [ ] Update test configurations for Spring Boot context

---

### 🐳 Containerization
- [ ] **Create optimized Dockerfile:**
```dockerfile
# Multi-stage build for optimal image size
FROM eclipse-temurin:17-jdk as builder
WORKDIR /app
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B
COPY src src
RUN ./mvnw clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
```

- [ ] **Create `.dockerignore`:**
```
target/
.mvn/
mvnw
mvnw.cmd
Dockerfile
.git/
.gitignore
README.md
```

### ☁️ Azure Container Registry Setup
- [ ] **Build and push to ACR:**
```bash
# Login to Azure
az login

# Create resource group
az group create --name rg-springboot --location eastasia

# Create ACR
az acr create --resource-group rg-springboot --name myacr --sku Basic

# Build and push image
az acr build --image springboot-api:1.0.0 --registry myacr --file Dockerfile .
```

### 📦 Azure Container Apps Deployment
- [ ] **Create ACA environment:**
```bash
# Install Container Apps extension
az extension add --name containerapp --upgrade

# Create Container Apps environment
az containerapp env create \
  --name aca-env \
  --resource-group rg-springboot \
  --location eastasia
```

- [ ] **Create deployment configuration (`springboot-containerapp.yaml`):**
```yaml
name: springboot-api
type: Microsoft.App/containerApps@2023-05-01
location: eastasia
properties:
  environmentId: /subscriptions/<subscription-id>/resourceGroups/rg-springboot/providers/Microsoft.App/managedEnvironments/aca-env
  configuration:
    ingress:
      external: true
      targetPort: 8080
      transport: auto
      allowInsecure: false
    registries:
      - server: myacr.azurecr.io
        identity: system
    secrets:
      - name: spring_profile
        value: "prod"
  template:
    containers:
      - name: springboot-api
        image: myacr.azurecr.io/springboot-api:1.0.0
        resources:
          cpu: 0.5
          memory: 1Gi
        env:
          - name: SPRING_PROFILES_ACTIVE
            secretRef: spring_profile
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
    scale:
      minReplicas: 1
      maxReplicas: 5
      rules:
        - name: http-scaling
          http:
            metadata:
              concurrentRequests: "100"
```

- [ ] **Deploy to Azure Container Apps:**
```bash
az containerapp create \
  --resource-group rg-springboot \
  --file springboot-containerapp.yaml
```

### 🎯 Database Setup (Production)
- [ ] **Create PostgreSQL Flexible Server:**
```bash
az postgres flexible-server create \
  --resource-group rg-springboot \
  --name postgres-springboot \
  --admin-user springbootuser \
  --admin-password YourSecurePassword123! \
  --location eastasia \
  --tier Burstable \
  --sku-name Standard_B1ms \
  --storage-size 32 \
  --version 14

# Configure firewall rules
az postgres flexible-server firewall-rule create \
  --resource-group rg-springboot \
  --name postgres-springboot \
  --rule-name AllowAzureServices \
  --start-ip-address 0.0.0.0 \
  --end-ip-address 0.0.0.0
```

### 🧹 Final Cleanup Tasks
- [ ] **Remove all AWS-related files:**
  - `template.yml` (AWS SAM template)
  - `build.gradle` (if migrating from Gradle)
  - Lambda handler classes
  - AWS SDK dependencies from `pom.xml`
  - AWS deployment scripts
- [ ] **Update documentation:**
  - README.md with new deployment instructions
  - Architecture documentation
  - API documentation
- [ ] **Archive old Lambda code for reference**
- [ ] **Update CI/CD pipelines for Azure deployment**

---

### 🏗️ Architecture Principles
- [ ] **Keep domain layer framework-free**
- [ ] **Use constructor-based dependency injection**
- [ ] **Use DTOs to isolate API contracts**
- [ ] **Enable OpenAPI docs for client clarity**
- [ ] **Avoid mixing responsibilities across layers**

### 🔧 Development Best Practices  
- [ ] **Follow clean logging (no sensitive data)**
- [ ] **Write unit and integration tests per function**
- [ ] **Use environment profiles for config separation**
- [ ] **Implement proper error handling with meaningful messages**
- [ ] **Use correlation IDs for request tracing**

### 🚀 Deployment Best Practices
- [ ] **Containerize with slim images (multi-stage builds)**
- [ ] **Implement health checks for container orchestration**
- [ ] **Use secrets management for sensitive configuration**
- [ ] **Enable monitoring and alerting**
- [ ] **Implement proper scaling policies**

---

### 🔧 Functional Requirements
- [ ] All original Lambda endpoints are working as REST APIs
- [ ] Database operations are functioning correctly
- [ ] External service integrations are working
- [ ] Error handling is comprehensive and user-friendly
- [ ] Input validation is working properly

### 📈 Performance Requirements
- [ ] Application startup time is acceptable
- [ ] Response times meet or exceed Lambda performance
- [ ] Memory usage is optimized
- [ ] Scaling works as expected under load

### 🔒 Security Requirements
- [ ] Input validation prevents injection attacks
- [ ] Sensitive data is not exposed in logs
- [ ] Environment variables are properly secured
- [ ] HTTPS is enforced in production

### 🧪 Quality Assurance
- [ ] Unit test coverage is 80%+
- [ ] Integration tests cover all endpoints
- [ ] Load testing completed successfully
- [ ] Security scanning shows no critical issues

### 📊 Operational Requirements
- [ ] Health checks are responding correctly
- [ ] Logging is structured and searchable
- [ ] Monitoring and alerting are configured
- [ ] Documentation is complete and up-to-date

---

## 📞 Support Information

- **API Documentation:** Available at `/swagger-ui.html` in development
- **Health Checks:** Available at `/actuator/health`
- **Metrics:** Available at `/actuator/metrics`
- **Environment Status:** Available at `/actuator/env`

---

**🎯 Estimated Timeline:** 2-3 weeks for complete migration  
**👥 Assigned To:** @jiratouchmhp  
**🔥 Priority:** High  
**🏷️ Labels:** `migration`, `spring-boot`, `azure`, `clean-architecture`, `enhancement`
